- need to past in the page content for the footer links
- signin footer page
- terms of use footer page.....might just be the same thing as terms of service?? 
     remove maybe
-About us picture missing
-Header carosel sizing different between pages
-Make spacing consistent everywhere
-Gray container on meet our team and our mission (might keep change color) Add to all maybe :interrobang:
-Add button to contact page
-Make phone number the same everywhere
     -Help page and Contact us (123) 456-7890
-Fix all spacing on Track Your Order
-Hyper link mentions of other pages to said other pages
     -FAQS
-Make carosel work